### ISSUE TITLE
Can't download svg with xlink:href

### ISSUE THREAD

**Issue by backsideofdawn** [rossmoody/svg-gobbler#139]
I downloaded this extension to get some svgs from the NYTimes tiles game, and the extension doesn't seem to work with getting the svgs. It shows a preview of what it's going to look like before I download, but when I download and open it, it just says: `error on line 6 at column 35: Namespace prefix xlink for href on use is not defined`. I tried a different svg grabber extension tool, and it also didn't work. Is there any way to download svgs that have `xlink:href` in them?

**Comment by rossmoody** [comment]
What the link of the site you're trying to download from. I'll look into this

**Comment by WriteThatDown** [comment]
The link of the website is [https://www.nytimes.com/puzzles/tiles](url)

**Comment by rossmoody** [comment]
@backsideofdawn I've been using that link to test for weeks now. It's such a good test site. I think it's extra good because they intentionally set the `viewBoxes` to 0 0 0 0 to hide them initially. 

Anyway, I'd be very interested to hear how 5.0 is working for ya on this front. I believe the issue was the dom parser can't parse strings with an xlink:href in it (might be because it's deprecated).

**Comment by backsideofdawn** [comment]
Since I last used the extension, I see it's had lots of improvements, and everything seems to be working great.
