### ISSUE TITLE
Support for refreshing the page (⌘-R)

### ISSUE THREAD

**Issue by chrismessina** [rossmoody/svg-gobbler#69]
**Describe the bug**
Refreshing the page using ⌘-R clears the source of SVGs and doesn't rerun the extraction process.

**To Reproduce**
1. Launch SVG Grabber to open a new page with extracted SVG assets
2. Hit ⌘-R 
3. See empty page

**Expected behavior**
1. Launch SVG Grabber to open a new page with extracted SVG assets
2. Hit ⌘-R 
3. See page of refreshed assets (including any newly detected assets)

**Screenshots**
First load:
![image](https://user-images.githubusercontent.com/22610/103141209-25586e80-46a6-11eb-8422-097386c42ede.png)

After refresh:
![image](https://user-images.githubusercontent.com/22610/103141203-12459e80-46a6-11eb-8d13-2287295a00cd.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.1 (20C69)
 - Browser: Chrome
 - Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by rossmoody** [comment]
OooOOooo, this is a fun one. Going to try to figure this out.

**Comment by rossmoody** [comment]
This is such an interesting problem and I'm unsure how to fix it. The problem I'm running into in my approach is in order to re-render after a refresh I need to be constantly listening with `chrome.tabs.onUpdated.addListener` logic and I don't like that cause I don't want to be listening in the background. Right now the extension loads the listener when the extension icon is pressed and then removes it immediately after the tab's page load is "complete".

I was thinking there might be an avenue with sessionStorage but I think it would still require listening to every page refresh. Hmmmm...

**Comment by chrismessina** [comment]
You couldn't run SVG Gobbler as a page overlay, could you? i.e. render it into the DOM where the icon is pressed?

**Comment by rossmoody** [comment]
It's funny you say that, SVG Gobbler started out that way (opening on the same page like a full screen modal). Competing with styles on the same page was difficult though and led to a lot of bugs. Gonna keep this open for now cause I'm sure there's a fix, but I'm not seasoned enough to do it.

**Comment by chrismessina** [comment]
Yeah, makes sense! Ugh, Chrome Extensions!
