### ISSUE TITLE
Stopped working at storyboardthat.com

### ISSUE THREAD

**Issue by larjohn** [rossmoody/svg-gobbler#73]
**Describe the bug**
While at https://www.storyboardthat.com/storyboard-creator, when the extension button is clicked, nothing seems to happen. 

**To Reproduce**
1. Go to https://www.storyboardthat.com/storyboard-creator
2. Click on the SVG Gobbler file
3. Open the web console
```
gather.js:1 Uncaught (in promise) TypeError: Cannot read property 'tagName' of null
    at o.determineType (gather.js:1)
    at gather.js:1
    at Array.map (<anonymous>)
    at h (gather.js:1)
    at gather.js:1
```

**Expected behavior**
SVG Gobbler should show some svg images from the page

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome, Edge (Chromium-based)
 - Version 90

**Additional context**
It seems that some element (named as a var t) gets null while enumerating

**Comment by NAjustin** [comment]
This is also happening in (most) Google Data Studio dashboards in the current build, but seems to depend on which chart types are used. The resulting error in this case is the same as OP mentioned:
```
Uncaught (in promise) TypeError: Cannot read property 'tagName' of null
    at o.determineType (gather.js:1)
    at gather.js:1
    at Array.map (<anonymous>)
    at h (gather.js:1)
    at gather.js:1
```

The generalized issue is that there's an unsafe check in `determineType` that fails if SVGs are present in the page that **don't have any child elements in them**. For Google Data Studio, this is a problem because they populate placeholder elements that look like this:
```
<svg class="metric-axis-holder" style="position: absolute; top: 115px; left: 0px; width: 1340px; height: 28px;"></svg>
```
. . . which is why the unsafe check against `origEle.firstElementChild.tagName` fails resulting in the aforementioned error.

@rossmoody I'll try to get a PR in for this if I have time, but if you beat me to a fix I'm thinking once these are safely checked it should default to the right case (although I'm thinking that the sprite detection is a little funny for GDS SVGs right now as well).

Here's a public dashboard template from SuperMetrics that can also be used to replicate/test the issue:
https://datastudio.google.com/u/0/reporting/1gQmJkWhBwfT1FFrJDWsFhJnctSiFP86L/page/ilCtB
