### ISSUE TITLE
SVG Gobbler won't work in some websites

### ISSUE THREAD

**Issue by Scratchfangs** [rossmoody/svg-gobbler#80]
https://www.vectorizer.io doesn't work.

**Comment by NAjustin** [comment]
This is also true of (most) Google Data Studio dashboards in the current build, but seems to depend on which chart types are used. The resulting error in this case is:
```
Uncaught (in promise) TypeError: Cannot read property 'tagName' of null
    at o.determineType (gather.js:1)
    at gather.js:1
    at Array.map (<anonymous>)
    at h (gather.js:1)
    at gather.js:1
```

The generalized issue is that there's an unsafe check in `determineType` that fails if SVGs are present in the page that don't have any child elements in them. For Google Data Studio, this is a problem because they populate placeholder elements that look like this:
```
<svg class="metric-axis-holder" style="position: absolute; top: 115px; left: 0px; width: 1340px; height: 28px;"></svg>
```
. . . which is why the unsafe check against `origEle.firstElementChild.tagName` fails resulting in the aforementioned error.

@rossmoody I'll try to get a PR in for this if I have time, but if you beat me to a fix I'm thinking once these are safely checked it should default to the right case (although I'm thinking that the sprite detection is a little funny for GDS SVGs right now as well).

Here's a public dashboard template from SuperMetrics that can be used to replicate/test the issue:
https://datastudio.google.com/u/0/reporting/1gQmJkWhBwfT1FFrJDWsFhJnctSiFP86L/page/ilCtB
